[tools]
node = "lts"
ruby = "latest"
deno = "latest"
flutter = "latest"
usage = "latest"
dart = "latest"
"pipx:argcomplete" = "latest"
"pipx:black" = "latest"
"pipx:poetry" = "latest"
python = "3.13.0"

[settings]
experimental = true
disable_hints = ["false"]
